#!/bin/bash
# desc: Make all scripts in ~/dotfiles/scripts executable

for file in ~/dotfiles/scripts/*; do
  if [ -f "$file" ]; then
    echo "Making executable: $file"
    chmod +x "$file"
  fi
done